### ISSUE TITLE
Manifest parser not working

### ISSUE THREAD

**Issue by mhmdar** [AhmadBadir/Downloader#4]
@AhmadBadir

The manifest parser is not working properly.
I believe that the segment link is not being saved in the array list as it should be.

I filed the bug on BugZilla under report # 99565:
[https://bugs.freedesktop.org/show_bug.cgi?id=99565](url)
using  @ahmadqamhiyeh 's BugZilla account

**Comment by AhmadBadir** [comment]
fixed.
